-- Auto-generated by seed-from-excel.ts
-- Seed pilares and bloques
-- Generated: 2026-03-27T14:12:54.946Z

DO $$
DECLARE
  v_pilar_seguridad uuid;
BEGIN
  INSERT INTO pilares (id, nombre, orden, color, icono)
  VALUES (gen_random_uuid(), 'Seguridad', 1, '#EF4444', 'ShieldAlert')
  RETURNING id INTO v_pilar_seguridad;

  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'SIF Y GESTIÓN DE INCIDENTES', 1);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'GESTIÓN DE PROCESOS DE ALTO RIESGO', 2);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'SEGURIDAD EN EL TRANSPORTE EN EL LUGAR DE TRABAJO', 3);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'MANIPULACIÓN DE MATERIALES Y ERGONOMÍA', 4);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'SUSTANCIAS PELIGROSAS', 5);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'ESPACIO CONFINADO', 6);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'PREVENCIÓN DE VIOLENCIA', 7);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'SEGURIDAD VIAL Y DE CONDUCCIÓN', 8);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'TRABAJO EN ALTURA', 9);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'LOTO/SAM', 10);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'SALUD OCUPACIONAL', 11);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'RESPUESTA ANTE EMERGENCIAS', 12);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'FORMACIÓN Y COMPETENCIA', 13);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'GESTIÓN PARA MANTENER', 14);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'GESTIÓN DE LA SEGURIDAD OPERACIONAL', 15);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'GESTIÓN DEL TRABAJO NO ESTÁNDAR', 16);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'GESTIÓN PARA MEJORAR', 17);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_seguridad, 'GESTIÓN DEL COMPORTAMIENTO', 18);
END $$;

DO $$
DECLARE
  v_pilar_gente uuid;
BEGIN
  INSERT INTO pilares (id, nombre, orden, color, icono)
  VALUES (gen_random_uuid(), 'Gente', 2, '#3B82F6', 'Users')
  RETURNING id INTO v_pilar_gente;

  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'CULTURA', 1);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'RECLUTAMIENTO Y SELECCIÓN', 2);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'RECOMPENSAS Y RECONOCIMIENTO', 3);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'APRENDIZAJE Y DESARROLLO', 4);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'GESTIÓN PARA MANTENER', 5);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'AMBIENTE DE TRABAJO Y ENGAGEMENT', 6);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'TALENTO Y CRECIMIENTO', 7);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'GESTIÓN PARA MEJORAR', 8);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gente, 'EQUIPOS AUTÓNOMOS', 9);
END $$;

DO $$
DECLARE
  v_pilar_gestion uuid;
BEGIN
  INSERT INTO pilares (id, nombre, orden, color, icono)
  VALUES (gen_random_uuid(), 'Gestión', 3, '#8B5CF6', 'Target')
  RETURNING id INTO v_pilar_gestion;

  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gestion, 'STRATEGY', 1);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gestion, 'BUSINESS AND PROCESSES MAPPING', 2);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gestion, 'MANAGE TO SUSTAIN', 3);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gestion, 'ROUTINE MANAGEMENT (SDCA)', 4);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gestion, 'MANAGE TO IMPROVE', 5);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_gestion, 'MANAGEMENT BY OBJECTIVES (MBO)', 6);
END $$;

DO $$
DECLARE
  v_pilar_entrega uuid;
BEGIN
  INSERT INTO pilares (id, nombre, orden, color, icono)
  VALUES (gen_random_uuid(), 'Entrega', 4, '#F59E0B', 'Truck')
  RETURNING id INTO v_pilar_entrega;

  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_entrega, 'PROCESOS DE EJECUCIÓN DE ENTREGA', 1);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_entrega, 'EQUIPOS EMPORDERADOS', 2);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_entrega, 'GESTIÓN PARA MANTENER', 3);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_entrega, 'EFICIENCIA DE PROCESOS', 4);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_entrega, 'SATISFACCIÓN DEL CLIENTE', 5);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_entrega, 'GESTIÓN PARA MEJORAR', 6);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_entrega, 'MEJORAS DE ENTREGA', 7);
END $$;

DO $$
DECLARE
  v_pilar_flota uuid;
BEGIN
  INSERT INTO pilares (id, nombre, orden, color, icono)
  VALUES (gen_random_uuid(), 'Flota', 5, '#10B981', 'Wrench')
  RETURNING id INTO v_pilar_flota;

  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_flota, 'COMPLIANCE', 1);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_flota, 'MANAGE TO SUSTAIN', 2);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_flota, 'CONFIABILIDAD DE LA FLOTA', 3);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_flota, 'GESTIÓN DE FLOTA', 4);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_flota, 'GESTIÓN PARA MEJORAR', 5);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_flota, 'AUTONOMÍA Y MEJORAS DE LA FLOTA', 6);
END $$;

DO $$
DECLARE
  v_pilar_almacen uuid;
BEGIN
  INSERT INTO pilares (id, nombre, orden, color, icono)
  VALUES (gen_random_uuid(), 'Almacén', 6, '#6366F1', 'Warehouse')
  RETURNING id INTO v_pilar_almacen;

  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'LAYOUT & CAPACIDAD', 1);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'CALIDAD', 2);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'GESTIÓN DE INVENTARIO', 3);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'GESTIÓN PARA MANTENER', 4);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'PICKING', 5);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'CARGA Y DESCARGA DE VEHÍCULOS DE DISTRIBUCIÓN', 6);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'REAPROVISIONAMIENTO', 7);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'GESTIÓN PARA MEJORAR', 8);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_almacen, 'MEJORAS DE PRODUCTIVIDAD', 9);
END $$;

DO $$
DECLARE
  v_pilar_planeamiento uuid;
BEGIN
  INSERT INTO pilares (id, nombre, orden, color, icono)
  VALUES (gen_random_uuid(), 'Planeamiento', 7, '#EC4899', 'CalendarClock')
  RETURNING id INTO v_pilar_planeamiento;

  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_planeamiento, 'GESTIÓN DE PRESUPUESTO', 1);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_planeamiento, 'GESTIÓN DE RIESGOS', 2);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_planeamiento, 'GESTIÓN PARA MANTENER', 3);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_planeamiento, 'PLANEAMIENTO A CORTO PLAZO', 4);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_planeamiento, 'CLIENTE EN EL CENTRO', 5);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_planeamiento, 'GESTIÓN PARA MEJORAR', 6);
  INSERT INTO bloques (id, pilar_id, nombre, orden)
  VALUES (gen_random_uuid(), v_pilar_planeamiento, 'PLANEAMIENTO A MEDIANO PLAZO', 7);
END $$;

